### ISSUE TITLE
Custom slack interrupt message when an interrupt is set

### ISSUE THREAD

**Issue by ameowlia** [dpb587/slack-delegate-bot#10]
There is an "empty_message" field in the yaml configuration for what to say when no interrupt is set. However there is no customizable "message" field. 

It would be great if we could customize our messages. I want to use it to set expectations (ex. "we should respond within 3 hours") and to share docs (ex. "while you wait on the interrupt, we recommend looking at these docs for the answer you need"). 

It could look something like this: 

![Screen Shot 2020-09-17 at 5 01 59 PM](https://user-images.githubusercontent.com/7025605/93528430-51768d80-f908-11ea-828e-fe46701a93b9.png)

**Comment by dpb587-pivotal** [comment]
Hi - thanks for the example. I've seen a few teams hack around it to similar effect, but it would be nice to make it cleaner and a bit more featureful. I'll add it to the queue - I keep meaning to get back to interrupt for some improvements like this.

As you may have found, you can currently add a `literal` value with arbitrary text before or after your interupt-lookups to have it included, but it doesn't work too well when no interrupt ends up being found. For example, something like the following:

```yaml
delegate:
  union:
  - literal: |
      Hi! We will try to get back to you before end of day today. In the meantime, we recommend checking our docs: https://www.google.com/
      ^ 
  - user: { id: U1234567 }
```
